- docs/getting-started.md
- docs/userguide/Clients.md
- lib/OpenCloud/Common/Base.php
- lib/OpenCloud/Common/Service/CatalogService.php
- lib/OpenCloud/Identity/Service.php
- lib/OpenCloud/OpenStack.php
- tests/OpenCloud/Tests/OpenStackTest.php
Inject the `Logger` into the `Service` when the `Client` already has one.
Also allow passing a PSR-3 Logger via the `$options` array in the `OpenStack` constructor.
Added tests to ensure that all services that can be created using the `OpenStack` class do support this.
> Inject Logger in service when available in Client

- apigen.neon
This config file changes the theme to bootstrap from the default and only documents `public` methods and properties.
> Adding apigen config file

- docs/userguide/Clients.md
FAO @ycombinator @everett-toews 
Fixes #539
> Adding explanation for prefixing user-agents

- docs/userguide/ObjectStore/USERGUIDE.md
- lib/OpenCloud/ObjectStore/Enum/ReturnType.php
- lib/OpenCloud/ObjectStore/Resource/Container.php
- tests/OpenCloud/Tests/ObjectStore/Resource/ContainerTest.php
In #545, I provided a workaround for what the user was requesting. This PR provides a more robust solution.
Fixes #545.
Attn: @jamiehannaford
> Return array of DataObjects if such is requested.

- docs/userguide/Networking/USERGUIDE.md
- lib/OpenCloud/Networking/Resource/Network.php
- lib/OpenCloud/Networking/Resource/Port.php
- lib/OpenCloud/Networking/Resource/SecurityGroup.php
- lib/OpenCloud/Networking/Resource/SecurityGroupRule.php
- lib/OpenCloud/Networking/Service.php
- samples/Networking/create-security-group-rule.php
- samples/Networking/create-security-group.php
- samples/Networking/delete-security-group-rule.php
- samples/Networking/delete-security-group.php
- samples/Networking/get-security-group-rule.php
- samples/Networking/get-security-group.php
- samples/Networking/list-security-group-rules.php
- samples/Networking/list-security-groups.php
- tests/OpenCloud/Smoke/Unit/Networking.php
- tests/OpenCloud/Tests/Networking/NetworkingTestCase.php
- tests/OpenCloud/Tests/Networking/ServiceTest.php
> [WIP] Neutron Security Groups + Security Group Rules

- lib/OpenCloud/Database/Service.php
- tests/OpenCloud/Tests/Database/DatabaseTestCase.php
- tests/OpenCloud/Tests/Database/ServiceTest.php
- tests/OpenCloud/Tests/MockLogger.php
- tests/OpenCloud/Tests/RackspaceTest.php
See https://github.com/rackspace/php-opencloud/issues/560#issuecomment-81790778.
Fixes #560 (temporarily).
> Using custom cipher suite for Rackspace Cloud Databases service

- doc/services/object-store/objects.rst
- samples/ObjectStore/list-objects-over-10000.php
Added an example of how to retrieve large data sets, based on http://stackoverflow.com/questions/18193501/rackspace-php-opencloud-filters-documentation-for-valid-objectlist-filters
> Added example of how to retrieve more than 10,000 objects

- doc/services/object-store/objects.rst
- lib/OpenCloud/Common/Constants/Header.php
- lib/OpenCloud/ObjectStore/Exception/ObjectNotEmptyException.php
- lib/OpenCloud/ObjectStore/Resource/DataObject.php
- samples/ObjectStore/symlink-object.php
- tests/OpenCloud/Tests/ObjectStore/Resource/DataObjectTest.php
> Added symlink functionality via X-Object-Manifest header management

- doc/services/dns/domains.rst
> Fixing add, modify, and remove records links.

- lib/OpenCloud/Common/Exceptions/DomainNotFoundException.php
- lib/OpenCloud/DNS/Service.php
- tests/OpenCloud/Tests/DNS/ServiceTest.php
> Adding convenience method to retrieve domain by name.

- lib/OpenCloud/Compute/Service.php
Update the documentation for some of the methods in the `\OpenCloud\Compute\Service` class.
Modify the `@return` statements to the correct object type.
This mostly benefits those using IDEs that depend on `@return` to help with code-completion. However, it also benefits anyone reviewing the documentation inline, so that they know the correct object to expect.
PR is this risk because only documentation is being updated.
> Update documentation for \OpenCloud\Compute\Service

- doc/services/object-store/migrating-containers.rst
Object store documentation is displaying the incorrect url type. It says 'privateURL’ but it should be ‘internalURL’.
> Changed 'privateURL' to 'internalURL'

- lib/OpenCloud/ObjectStore/Resource/DataObject.php
- tests/OpenCloud/Tests/ObjectStore/Resource/DataObjectTest.php
> Provide the option to override inherited URL types for temp URLs

- lib/OpenCloud/Networking/Resource/Port.php
Allows the \OpenCloud\Networking\Resource\Port::update() method to affect security groups, as per API and library documentation. Currently the 'securityGroups' option is silently ignored. 
Additional keys are also omitted in the `$updateKeys` property, but they are beyond the scope of this pull-request:
```
adminStateUp
fixedIps
deviceOwner
```
> Allow port update() to modify security groups.

- samples/Compute/create_server_with_keypair.php
In the "create_server_with_keypair" sample, the keypair is missing.
> Fix "create_server_with_keypair" sample

- lib/OpenCloud/ObjectStore/Resource/DataObject.php
The type returned from `DataObject.contentLength` varies based on how the object
is populated. This change ensures that when 'setContentLength' is called
the property is set to the expected type (int).
It seems like this could be solved a number of ways, but this seemed like the  "silver bullet". At first glance it seems the problematic code is in the two `populate*` methods on the object. `populate` seems to be given a string for the [`$info->bytes`](https://github.com/rackspace/php-opencloud/blob/f080c2feffb64b544ecefa3d1b200b5c16a5a797/lib/OpenCloud/ObjectStore/Resource/DataObject.php#L119) and `populateFromResponse` is [explicitly cast to a string](https://github.com/rackspace/php-opencloud/blob/f080c2feffb64b544ecefa3d1b200b5c16a5a797/lib/OpenCloud/ObjectStore/Resource/DataObject.php# …
> hotfix – DataObject->setContentLength : Ensure int

- lib/OpenCloud/Queues/Service.php
I believe this does not require explaining :)
ps there are other issues in this class but I will make separate PRs once I get it running
> Fixed missing use statement and php doc in Queues/Service

- doc/services/object-store/access.rst
I propose to add instructions override TempURL file names, it took me some time to figure out how to do it. It is mentioned in the Rackspace cloud files developer guide (http://docs.rackspace.com/files/api/v1/cf-devguide/content/TempURL_File_Name_Overrides-d1e213.html) but I could find no mention in this documentation. I found  the solution in a blog post from 2013: http://blog.rackspace.com/cloud-files-update-new-api-only-and-control-panel-features/?cm_mmc=Social-_-FaceBook-_-Blog-_-CustRef&sf13063985=1
I tried it, it works.
> override TempURL file names

- composer.json
This will prevent people that require the library in composer getting the tests in their optimised composer classmap.
> Autoload tests only for dev

- lib/OpenCloud/Compute/Resource/Server.php
- tests/OpenCloud/Tests/Compute/Resource/ServerTest.php
Implementation and code style based on the `$networks` part above it.
Todo: documentation.
Fixes #516
> Add support for security groups on server create

- lib/OpenCloud/ObjectStore/Resource/DataObject.php
- tests/OpenCloud/Tests/ObjectStore/Resource/DataObjectTest.php
Should fix #648
Using `combine` didn't work, as it would either override the path info, or would override the external host info with the internal host, depending on order of combine.
> Fix temp public URL missing file path info
